// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUMS_PACKETS_H_
#define FLATBUFFERS_GENERATED_ENUMS_PACKETS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 24,
             "Non-compatible flatbuffers version included");

namespace Packets {

enum PacketTypes : uint8_t {
  PacketTypes_PT_PLAYER_EXIT_CS = 0,
  PacketTypes_PT_PLAYER_ENTER_INGAME = 1,
  PacketTypes_PT_PLAYER_INPUT_CS = 2,
  PacketTypes_PT_PLAYER_LOOK_CS = 3,
  PacketTypes_PT_PLAYER_SELECT_WEAPON_CS = 4,
  PacketTypes_PT_PLAYER_SELECT_ROLE_CS = 5,
  PacketTypes_PT_LATENCY_CS = 6,
  PacketTypes_PT_REQUEST_USE_ITEM_CS = 7,
  PacketTypes_PT_REQUEST_ATTACK_CS = 8,
  PacketTypes_PT_REQUEST_FIRE_CS = 9,
  PacketTypes_PT_PROTOCOL_VERSION_SC = 128,
  PacketTypes_PT_NOTIFY_ID_SC = 129,
  PacketTypes_PT_PLAYER_EXIT_SC = 130,
  PacketTypes_PT_LATENCT_SC = 131,
  PacketTypes_PT_OBJECT_APPEARED_SC = 132,
  PacketTypes_PT_OBJECT_DISAPPEARED_SC = 133,
  PacketTypes_PT_OBJECT_REMOVED_SC = 134,
  PacketTypes_PT_OBJECT_MOVE_SC = 135,
  PacketTypes_PT_OBJECT_ATTACKED_SC = 136,
  PacketTypes_PT_OBJECT_ANIMATION_CHANGED_SC = 137,
  PacketTypes_PT_GEM_INTERACT_SC = 138,
  PacketTypes_PT_GEM_CANCEL_INTERACTOIN_SC = 139,
  PacketTypes_PT_GEM_DESTROYED_SC = 140,
  PacketTypes_PT_USE_ITEM_SC = 141,
  PacketTypes_PT_ACQUIRED_ITEM_SC = 142,
  PacketTypes_PT_FIRE_PROJECTILE_SC = 143,
  PacketTypes_PT_PROJECTILE_MOVE_SC = 144,
  PacketTypes_MIN = PacketTypes_PT_PLAYER_EXIT_CS,
  PacketTypes_MAX = PacketTypes_PT_PROJECTILE_MOVE_SC
};

inline const PacketTypes (&EnumValuesPacketTypes())[27] {
  static const PacketTypes values[] = {
    PacketTypes_PT_PLAYER_EXIT_CS,
    PacketTypes_PT_PLAYER_ENTER_INGAME,
    PacketTypes_PT_PLAYER_INPUT_CS,
    PacketTypes_PT_PLAYER_LOOK_CS,
    PacketTypes_PT_PLAYER_SELECT_WEAPON_CS,
    PacketTypes_PT_PLAYER_SELECT_ROLE_CS,
    PacketTypes_PT_LATENCY_CS,
    PacketTypes_PT_REQUEST_USE_ITEM_CS,
    PacketTypes_PT_REQUEST_ATTACK_CS,
    PacketTypes_PT_REQUEST_FIRE_CS,
    PacketTypes_PT_PROTOCOL_VERSION_SC,
    PacketTypes_PT_NOTIFY_ID_SC,
    PacketTypes_PT_PLAYER_EXIT_SC,
    PacketTypes_PT_LATENCT_SC,
    PacketTypes_PT_OBJECT_APPEARED_SC,
    PacketTypes_PT_OBJECT_DISAPPEARED_SC,
    PacketTypes_PT_OBJECT_REMOVED_SC,
    PacketTypes_PT_OBJECT_MOVE_SC,
    PacketTypes_PT_OBJECT_ATTACKED_SC,
    PacketTypes_PT_OBJECT_ANIMATION_CHANGED_SC,
    PacketTypes_PT_GEM_INTERACT_SC,
    PacketTypes_PT_GEM_CANCEL_INTERACTOIN_SC,
    PacketTypes_PT_GEM_DESTROYED_SC,
    PacketTypes_PT_USE_ITEM_SC,
    PacketTypes_PT_ACQUIRED_ITEM_SC,
    PacketTypes_PT_FIRE_PROJECTILE_SC,
    PacketTypes_PT_PROJECTILE_MOVE_SC
  };
  return values;
}

inline const char *EnumNamePacketTypes(PacketTypes e) {
  switch (e) {
    case PacketTypes_PT_PLAYER_EXIT_CS: return "PT_PLAYER_EXIT_CS";
    case PacketTypes_PT_PLAYER_ENTER_INGAME: return "PT_PLAYER_ENTER_INGAME";
    case PacketTypes_PT_PLAYER_INPUT_CS: return "PT_PLAYER_INPUT_CS";
    case PacketTypes_PT_PLAYER_LOOK_CS: return "PT_PLAYER_LOOK_CS";
    case PacketTypes_PT_PLAYER_SELECT_WEAPON_CS: return "PT_PLAYER_SELECT_WEAPON_CS";
    case PacketTypes_PT_PLAYER_SELECT_ROLE_CS: return "PT_PLAYER_SELECT_ROLE_CS";
    case PacketTypes_PT_LATENCY_CS: return "PT_LATENCY_CS";
    case PacketTypes_PT_REQUEST_USE_ITEM_CS: return "PT_REQUEST_USE_ITEM_CS";
    case PacketTypes_PT_REQUEST_ATTACK_CS: return "PT_REQUEST_ATTACK_CS";
    case PacketTypes_PT_REQUEST_FIRE_CS: return "PT_REQUEST_FIRE_CS";
    case PacketTypes_PT_PROTOCOL_VERSION_SC: return "PT_PROTOCOL_VERSION_SC";
    case PacketTypes_PT_NOTIFY_ID_SC: return "PT_NOTIFY_ID_SC";
    case PacketTypes_PT_PLAYER_EXIT_SC: return "PT_PLAYER_EXIT_SC";
    case PacketTypes_PT_LATENCT_SC: return "PT_LATENCT_SC";
    case PacketTypes_PT_OBJECT_APPEARED_SC: return "PT_OBJECT_APPEARED_SC";
    case PacketTypes_PT_OBJECT_DISAPPEARED_SC: return "PT_OBJECT_DISAPPEARED_SC";
    case PacketTypes_PT_OBJECT_REMOVED_SC: return "PT_OBJECT_REMOVED_SC";
    case PacketTypes_PT_OBJECT_MOVE_SC: return "PT_OBJECT_MOVE_SC";
    case PacketTypes_PT_OBJECT_ATTACKED_SC: return "PT_OBJECT_ATTACKED_SC";
    case PacketTypes_PT_OBJECT_ANIMATION_CHANGED_SC: return "PT_OBJECT_ANIMATION_CHANGED_SC";
    case PacketTypes_PT_GEM_INTERACT_SC: return "PT_GEM_INTERACT_SC";
    case PacketTypes_PT_GEM_CANCEL_INTERACTOIN_SC: return "PT_GEM_CANCEL_INTERACTOIN_SC";
    case PacketTypes_PT_GEM_DESTROYED_SC: return "PT_GEM_DESTROYED_SC";
    case PacketTypes_PT_USE_ITEM_SC: return "PT_USE_ITEM_SC";
    case PacketTypes_PT_ACQUIRED_ITEM_SC: return "PT_ACQUIRED_ITEM_SC";
    case PacketTypes_PT_FIRE_PROJECTILE_SC: return "PT_FIRE_PROJECTILE_SC";
    case PacketTypes_PT_PROJECTILE_MOVE_SC: return "PT_PROJECTILE_MOVE_SC";
    default: return "";
  }
}

enum AnimationState : uint8_t {
  AnimationState_IDLE = 0,
  AnimationState_MOVE_FORWARD = 1,
  AnimationState_MOVE_BACKWARD = 2,
  AnimationState_MOVE_LEFT = 3,
  AnimationState_MOVE_RIGHT = 4,
  AnimationState_JUMP = 5,
  AnimationState_ATTACKED = 6,
  AnimationState_ATTACK = 7,
  AnimationState_INTERACTION = 8,
  AnimationState_DEAD = 9,
  AnimationState_MIN = AnimationState_IDLE,
  AnimationState_MAX = AnimationState_DEAD
};

inline const AnimationState (&EnumValuesAnimationState())[10] {
  static const AnimationState values[] = {
    AnimationState_IDLE,
    AnimationState_MOVE_FORWARD,
    AnimationState_MOVE_BACKWARD,
    AnimationState_MOVE_LEFT,
    AnimationState_MOVE_RIGHT,
    AnimationState_JUMP,
    AnimationState_ATTACKED,
    AnimationState_ATTACK,
    AnimationState_INTERACTION,
    AnimationState_DEAD
  };
  return values;
}

inline const char * const *EnumNamesAnimationState() {
  static const char * const names[11] = {
    "IDLE",
    "MOVE_FORWARD",
    "MOVE_BACKWARD",
    "MOVE_LEFT",
    "MOVE_RIGHT",
    "JUMP",
    "ATTACKED",
    "ATTACK",
    "INTERACTION",
    "DEAD",
    nullptr
  };
  return names;
}

inline const char *EnumNameAnimationState(AnimationState e) {
  if (::flatbuffers::IsOutRange(e, AnimationState_IDLE, AnimationState_DEAD)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAnimationState()[index];
}

enum PlayerRole : uint8_t {
  PlayerRole_HUMAN = 0,
  PlayerRole_BOSS = 1,
  PlayerRole_MIN = PlayerRole_HUMAN,
  PlayerRole_MAX = PlayerRole_BOSS
};

inline const PlayerRole (&EnumValuesPlayerRole())[2] {
  static const PlayerRole values[] = {
    PlayerRole_HUMAN,
    PlayerRole_BOSS
  };
  return values;
}

inline const char * const *EnumNamesPlayerRole() {
  static const char * const names[3] = {
    "HUMAN",
    "BOSS",
    nullptr
  };
  return names;
}

inline const char *EnumNamePlayerRole(PlayerRole e) {
  if (::flatbuffers::IsOutRange(e, PlayerRole_HUMAN, PlayerRole_BOSS)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPlayerRole()[index];
}

enum EntityType : uint8_t {
  EntityType_ENV = 0,
  EntityType_HUMAN = 1,
  EntityType_BOSS = 2,
  EntityType_MONSTER = 3,
  EntityType_CORRUPTED_GEM = 4,
  EntityType_PROJECTILE = 5,
  EntityType_MIN = EntityType_ENV,
  EntityType_MAX = EntityType_PROJECTILE
};

inline const EntityType (&EnumValuesEntityType())[6] {
  static const EntityType values[] = {
    EntityType_ENV,
    EntityType_HUMAN,
    EntityType_BOSS,
    EntityType_MONSTER,
    EntityType_CORRUPTED_GEM,
    EntityType_PROJECTILE
  };
  return values;
}

inline const char * const *EnumNamesEntityType() {
  static const char * const names[7] = {
    "ENV",
    "HUMAN",
    "BOSS",
    "MONSTER",
    "CORRUPTED_GEM",
    "PROJECTILE",
    nullptr
  };
  return names;
}

inline const char *EnumNameEntityType(EntityType e) {
  if (::flatbuffers::IsOutRange(e, EntityType_ENV, EntityType_PROJECTILE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEntityType()[index];
}

enum Weapon : uint8_t {
  Weapon_SWORD = 0,
  Weapon_BOW = 1,
  Weapon_SPEAR = 2,
  Weapon_STAFF = 3,
  Weapon_MIN = Weapon_SWORD,
  Weapon_MAX = Weapon_STAFF
};

inline const Weapon (&EnumValuesWeapon())[4] {
  static const Weapon values[] = {
    Weapon_SWORD,
    Weapon_BOW,
    Weapon_SPEAR,
    Weapon_STAFF
  };
  return values;
}

inline const char * const *EnumNamesWeapon() {
  static const char * const names[5] = {
    "SWORD",
    "BOW",
    "SPEAR",
    "STAFF",
    nullptr
  };
  return names;
}

inline const char *EnumNameWeapon(Weapon e) {
  if (::flatbuffers::IsOutRange(e, Weapon_SWORD, Weapon_STAFF)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWeapon()[index];
}

enum ItemType : uint8_t {
  ItemType_POTION = 0,
  ItemType_CROSS = 1,
  ItemType_HOLY_WATER = 2,
  ItemType_MIN = ItemType_POTION,
  ItemType_MAX = ItemType_HOLY_WATER
};

inline const ItemType (&EnumValuesItemType())[3] {
  static const ItemType values[] = {
    ItemType_POTION,
    ItemType_CROSS,
    ItemType_HOLY_WATER
  };
  return values;
}

inline const char * const *EnumNamesItemType() {
  static const char * const names[4] = {
    "POTION",
    "CROSS",
    "HOLY_WATER",
    nullptr
  };
  return names;
}

inline const char *EnumNameItemType(ItemType e) {
  if (::flatbuffers::IsOutRange(e, ItemType_POTION, ItemType_HOLY_WATER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesItemType()[index];
}

enum ProjectileTypes : uint8_t {
  ProjectileTypes_ARROW = 0,
  ProjectileTypes_MIN = ProjectileTypes_ARROW,
  ProjectileTypes_MAX = ProjectileTypes_ARROW
};

inline const ProjectileTypes (&EnumValuesProjectileTypes())[1] {
  static const ProjectileTypes values[] = {
    ProjectileTypes_ARROW
  };
  return values;
}

inline const char * const *EnumNamesProjectileTypes() {
  static const char * const names[2] = {
    "ARROW",
    nullptr
  };
  return names;
}

inline const char *EnumNameProjectileTypes(ProjectileTypes e) {
  if (::flatbuffers::IsOutRange(e, ProjectileTypes_ARROW, ProjectileTypes_ARROW)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesProjectileTypes()[index];
}

}  // namespace Packets

#endif  // FLATBUFFERS_GENERATED_ENUMS_PACKETS_H_
