// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKETPROTOCOL_H_
#define FLATBUFFERS_GENERATED_PACKETPROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 24,
             "Non-compatible flatbuffers version included");

#include "AttackSystem_generated.h"
#include "BaseStructures_generated.h"
#include "CommonObjects_generated.h"
#include "CorruptedGem_generated.h"
#include "Items_generated.h"
#include "Networks_generated.h"

#endif  // FLATBUFFERS_GENERATED_PACKETPROTOCOL_H_
